import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const base = process.env.VELUM_TEST_URL || 'http://127.0.0.1:8787';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Evaluate batch' }).click();
  await page.getByText('2 of 5 invoices approved').waitFor();
  assert.equal(await page.locator('#batch-approved').textContent(), '$5,800');
  assert.equal(await page.locator('#batch-isolated').textContent(), '$13,800');
  assert.equal(await page.locator('#batch-prevented').textContent(), '$8,000');
  assert.equal(await page.locator('#batch-rows tr').count(), 5);
  await page.getByRole('button', { name: 'Public report', exact: true }).click();
  assert.ok(!(await page.locator('#disclosure-content').textContent()).includes('NS-101'));
  assert.ok((await page.locator('#disclosure-content').textContent()).includes('commitment'));
  await page.getByRole('button', { name: 'Operator view', exact: true }).click();
  assert.ok((await page.locator('#disclosure-content').textContent()).includes('NS-101'));
  const downloadWait = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download preview receipt' }).click();
  assert.equal((await downloadWait).suggestedFilename(), 'velum-preview-receipt.json');
  await page.locator('#batch-budget').fill('10000');
  assert.equal(await page.locator('#batch-approved').textContent(), '—');
  await page.getByRole('button', { name: 'Evaluate batch' }).click();
  await page.getByText('3 of 5 invoices approved').waitFor();
  assert.equal(await page.locator('#batch-approved').textContent(), '$9,600');
  await page.getByText('✓ Receipt file integrity checked').waitFor();
  assert.equal(await page.locator('#balance-after').textContent(), '$14,200');
  await page.locator('#sepolia-proof').waitFor({ state: 'visible' });
  assert.match(await page.locator('#sepolia-summary').textContent(), /\$5,800 synthetic USD/);
  const testnet = await page.evaluate(async () => (await fetch('/sepolia-evidence.json')).json());
  assert.equal(await page.getByRole('link', { name: 'CRE report delivery' }).getAttribute('href'), `https://sepolia.etherscan.io/tx/${testnet.report.txHash}`);
  assert.equal(await page.locator('#sepolia-links a').count(), 4);
  await page.locator('.single-lab summary').click();
  await page.getByRole('button', { name: 'Evaluate invoice' }).click();
  await page.getByText('Approved by the preview policy').waitFor();
  await page.locator('[data-scenario="over-limit"]').click();
  await page.getByRole('button', { name: 'Evaluate invoice' }).click();
  await page.getByText('Rejected by the preview policy').waitFor();
  assert.match(await page.locator('#result').textContent(), /private approval limit/);
  for (const scenario of ['wrong-recipient', 'duplicate']) {
    await page.locator(`[data-scenario="${scenario}"]`).click();
    await page.getByRole('button', { name: 'Evaluate invoice' }).click();
    await page.getByText('Rejected by the preview policy').waitFor();
  }
  await page.locator('[data-scenario="approved"]').click();
  await page.locator('#limit').fill('2000');
  await page.getByRole('button', { name: 'Evaluate invoice' }).click();
  await page.getByText('Rejected by the preview policy').waitFor();
  await page.locator('#limit').fill('5000');
  await page.getByRole('button', { name: 'Evaluate invoice' }).click();
  await page.getByText('Approved by the preview policy').waitFor();
  assert.match(await page.locator('#execution-status').textContent(), /approved: APPROVE/);
  assert.match(await page.locator('#execution-status').textContent(), /wrong-recipient: REJECT/);
  mkdirSync('evidence', { recursive: true });
  await page.locator('.single-lab summary').click();
  await page.locator('#batch-budget').fill('6000');
  await page.getByRole('button', { name: 'Evaluate batch' }).click();
  await page.getByText('2 of 5 invoices approved').waitFor();
  await page.screenshot({ path: 'evidence/desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile horizontal overflow');
  await page.screenshot({ path: 'evidence/mobile.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ success: true, base, checks: ['batch budget reservation', 'independent-check comparison', 'duplicate held', 'private/public disclosure', 'receipt download', 'budget change invalidates stale preview', 'budget change recalculates decisions', 'recorded receipt SHA-256 verified', 'settlement balances visible', 'Sepolia receipt and explorer links', 'approval', 'over limit', 'wrong recipient', 'duplicate', 'changed threshold', 'recorded evidence visible', '390px mobile overflow', 'no page errors'] }, null, 2));
} finally { await browser.close(); }
